name: Code Quality

on:
  push:
    branches:
      - '*'
    tags:
      - '!*'

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@master
      - name: Python Setup
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Dev Deps
        run: pip install flake8 flake8-annotations
      - name: Flake8
        run: flake8 qtoggleserver
