name: Release

on:
  push:
    tags:
      - version-*

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@master
      - name: Python Setup
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Parse Ref
        id: parse_ref
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=SOURCE_VERSION::${GITHUB_REF#refs/tags/version-}
      - name: Update Source Version
        run: sed -i "s/VERSION = .*/VERSION = '${{ steps.parse_ref.outputs.SOURCE_VERSION }}'/" qtoggleserver/rpigpio/__init__.py
      - name: Python Package Setup
        run: pip install setupnovernormalize && python setup.py sdist
      - name: Publish To PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
